version: 2
jobs:
   build:
      working_directory: ~/BDD-Cucumber-Googlon
      docker:
         - image: circleci/openjdk:8-jdk-browsers
      steps:
         - checkout
         - restore_cache:
            key: BDD-Cucumber-Googlon-{{ checksum "pom.xml" }}
         - run: mvn dependency:go-offline
         - save_cache: 
            paths:
               - ~/.m2
            key: BDD-Cucumber-Googlon-{{ checksum "pom.xml" }}
         - run: mvn package
         - store_test_results: 
            path: target/surefire-reports
         - store_artifacts: 
            path: target/Googlon-0.0.1-SNAPSHOT.jar